apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Random Test Pipeline with Smart Tests
on:
  workflow_dispatch:
    inputs:
      iterations:
        description: Number of pipeline iterations to run
        type: string
        required: false
        default: '5'
  workflow_call:
permissions:
  scm-token-own: read
  scm-token-org: read
jobs:
  run-pipeline:
    steps:
      - name: Check out
        uses: cloudbees-io/checkout@v2
        with:
          path: source
          fetch-depth: 0

      - name: Run pipeline iterations
        uses: docker://cloudbees/smart-tests-cli:v2.0
        shell: sh
        env:
          SMART_TESTS_TOKEN: ${{ secrets.SMART_TESTS_KEY }}
          ITERATIONS: ${{ inputs.iterations || '5' }}
        run: |
          cd source

          echo "========================================"
          echo "Running Smart Tests Pipeline"
          echo "Iterations: $ITERATIONS"
          echo "========================================"
          echo ""

          # Configure git for commits during pipeline
          git config --global --add safe.directory /cloudbees/workspace/source
          git config --global user.email "ci@cloudbees.io"
          git config --global user.name "CloudBees CI"

          # Install Python and dependencies
          echo "Installing Python and dependencies..."
          pip3 install --quiet --user -r requirements.txt

          # Add pip user install location to PATH
          export PATH="/cloudbees/home/.local/bin:$PATH"

          # Run the pipeline with bash (script uses bash syntax)
          bash cicd/pipeline.sh $ITERATIONS

      - name: Archive final test results
        if: always()
        uses: cloudbees-io/publish-test-results@v2
        with:
          test-type: JUNIT
          results-path: source/cicd/temp/test-results/*.xml
